#!/usr/bin/env bash

# Simple tool to remove a git repo from somewhere. Just run `git deinit`

deinit_git() {
    REPO_PATH=$(git rev-parse --show-toplevel)
    if [[ -d "${REPO_PATH}/.git" ]]; then
        read -p "De-initialize this git repo? [y/N]" -n 1 -r
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            echo
            echo "Removing ${REPO_PATH}/.git…"
            rm -rf "${REPO_PATH}/.git"
            echo "Done ✓"
        else
            echo "Aborting…"
        fi
    else
        echo "Not in a git repository"
    fi
}
deinit_git
