#!/usr/bin/env bash
# Usage: git-edit [conflicted|staged|edited|commited]
# If no option is passed, edited is the default

main() {
    local action="$1"
    case $action in
    conflict | conflicts | conflicted)
        read -r -d ' ' -a files < <(git diff --name-only --diff-filter=U)
        ;;
    commited)
        read -r -d ' ' -a files < <(git diff HEAD^ --name-only --diff-filter=ACMR)
        ;;
    staged)
        read -r -d ' ' -a files < <(git diff --staged --name-only --diff-filter=ACMR)
        ;;
    edited)
        read -r -d ' ' -a files < <(git diff HEAD --name-only --diff-filter=ACMR)
        ;;
    *)
        read -r -d ' ' -a files < <(git diff HEAD --name-only --diff-filter=ACMR)
        return
        ;;
    esac
    if [[ -n ${files[*]} ]]; then
        $EDITOR "${files[@]}"
    else
        echo "No files match '${action}'"
    fi
}

main "$@"
