#!/usr/bin/env sh
echo "This will delete all tags for this repository, local and remote"
read -p "Do you want to continue? (y/N)" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi

# Taken from https://gist.github.com/okunishinishi/9424779
#Delete local tags.
git tag -l | xargs git tag -d
#Fetch remote tags.
git fetch
#Delete remote tags.
git tag -l | xargs git push --delete origin
#Delete local tags.
git tag -l | xargs git tag -d
