#!/usr/bin/env zsh

help_message() {
    echo  "USAGE: git ignore <files> <to> <ignore>"
    exit 1
}

main() {
    ((!$#)) && help_message && exit 1
    for file_to_ignore in "$@"; do
        echo "Ignored ${file_to_ignore}"
        echo "${file_to_ignore}" | tee -a '.gitignore'
    done;
}

main $@
