#!/usr/bin/env sh
# Kills all processes running on the specified port (e.g. 'killport 8080')
# Taken from https://github.com/ahmedelgabri/dotfiles/blob/master/extra/bin/killport

killport() {
  lsof -i tcp:"$1" | awk '(NR!=1) && ($1!="Google") && ($1!="firefox") {print $2}' | xargs kill
}

killport "$@"
